Added buy product flow
bitcapital-hq/marketplace-sample pull request #4
Opened 2019-01-25 18:45 UTC by danilomendes12

Added buy product flow

2019-01-28 13:45 UTC, danilomendes12 commented
Added api

2019-01-29 17:43 UTC, rangelfinal requested changes

2019-01-29 17:43 UTC, rangelfinal commented on api/controllers/AssetController.ts
> +        const user: User = await User.findById(req.body.userId);
Uma convenção que a gente segue no core é pegar todas as propriedades do body no começo da função.
Exemplo: ` const { userId, amount }: { userId: string, amount: number } = req.body` ([Usando destruturação](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment))
Isso facilita bastante na hora de escrever a documentação do endpoint, porque você já sabe o schema do body logo de cara.

2019-01-29 17:43 UTC, rangelfinal commented on api/controllers/UserController.ts
> +    return res.success(await ExtractService.getInstance({}).getBitcapitalExtractForUser(req.params.id));
Assim como a gente coloca as propriedades do body no começo da função, o mesmo vale pra params.
`const { id }: { id: string } = req.params` salva vidas e horas na hora de escrever documentação.

2019-01-29 17:43 UTC, rangelfinal commented on api/services/ProductService.ts
> +            throw new BaseError('Product quantity is invalid.', {quantity: quantity});
```suggestion
            throw new BaseError('Product quantity is invalid.', { quantity });
```
Você pode usar shorthand quando o nome da propriedade não muda

2019-01-29 17:43 UTC, rangelfinal commented on api/services/ProductService.ts
> +        if(productStorage == null || productStorage.quantity < quantity){
No geral, `==` nunca é o que você quer porque essa desgraça faz coerção e tem resultados bem inesperados
Use sempre `===`

2019-01-29 18:23 UTC, danilomendes12 commented on api/controllers/AssetController.ts
> +        const user: User = await User.findById(req.body.userId);
Legal, vou arrumar

2019-01-29 18:39 UTC, danilomendes12 commented on api/services/ProductService.ts
> +        if(productStorage == null || productStorage.quantity < quantity){
Ok, thx :D

2019-01-29 18:41 UTC, danilomendes12 commented on api/controllers/UserController.ts
> +    return res.success(await ExtractService.getInstance({}).getBitcapitalExtractForUser(req.params.id));
Fixed

2019-01-29 18:41 UTC, danilomendes12 commented on api/controllers/AssetController.ts
> +        const user: User = await User.findById(req.body.userId);
Fixed

2019-01-30 17:23 UTC, rangelfinal approved these changes

2019-01-30 18:11 UTC, merged