[WIP] User get balance and some code fixes
bitcapital-hq/marketplace-sample pull request #5
Opened 2019-01-28 13:46 UTC by danilomendes12

- Added getbalance endpoint and empty method
- Some minor code fixes

2019-01-31 19:25 UTC, rangelfinal requested changes

2019-01-31 19:25 UTC, rangelfinal commented on .vscode/launch.json
> +      "runtimeExecutable": "/Users/danilomendes/n/bin/node",
Adiciona seu node no seu path, ow

2019-01-31 19:25 UTC, rangelfinal commented on api/services/AssetService.ts
> +  private static assetId: string = "6ddbf2d9-172f-490b-bb30-71689efa6ccb";
Dá pra mover isso pro bitcapital.config pra não ficar tão feio

2019-01-31 19:25 UTC, rangelfinal commented on api/services/ProductService.ts
> +    return ProductStorage.save(storage[0]);
Esse `[0]` tá certo? `storage` não parece ser uma array aqui

2019-02-01 16:03 UTC, danilomendes12 commented on .vscode/launch.json
> +      "runtimeExecutable": "/Users/danilomendes/n/bin/node",
Eu adicionei...foi algum bug que ele não achou aqui, o @luiseduardobrito tentou ajudar e não conseguiu tb

2019-02-04 00:29 UTC, merged